######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 12:02:06 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testplus.h
SOURCES += testplus.cpp tst_ctestplus.cpp

QMAKE_CXXFLAGS += -g -Wall -fprofile-arcs -ftest-coverage -O0

QMAKE_LFLAGS += -g -Wall -fprofile-arcs -ftest-coverage  -O0

LIBS += -lgcov
