######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 4 12:07:23 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test1.h
SOURCES += test1.cpp tst_ut_template_1test.cpp
